tab_schemas = {
    "Agenda": ["Date", "Start Time", "End Time", "Title", "Details", "Location_Link", "Category", "Status", "Reminder", "Recurring", "Confirmed?"],
    "GPT_Memory": ["Date", "Log"],
    "Pending Uploads": ["Date", "Original Tab", "Field1", "Field2", "Field3", "Field4", "Field5", "Field6", "Status"],
    "Addresses": ["Name", "Street Address", "City_State_ZIP", "Notes"],
    "Shopping  Wishlist": ["Item", "Category", "Priority", "Link", "Notes"],
    "Books  Media": ["Title", "Type", "Status", "Notes"],
    "Finances": ["Date", "Category", "Description", "Amount", "Notes"],
    "Fitness  Health": ["Date", "Activity", "Duration", "Notes"],
    "Work  Projects": ["Project", "Task", "Due Date", "Status", "Notes"],
    "Birthdays  Anniversaries": ["Name", "Date", "Type", "Notes"],
    "Contacts  Networking": ["Name", "Company", "Role", "Notes", "Follow-Up Date"],
    "AI Requests": ["Date", "Request", "Status", "Response Notes"],
    "Archive": ["Original Tab", "Date Archived", "Title", "Details", "Status"],
    "Logs": ["Timestamp", "Action", "Details"],
    "Meta": ["Key", "Value", "Last Updated"],
    "Goals": ["Goal", "Start Date", "Target Date", "Progress", "Notes"],
    "Notes": ["Date", "Note", "Tags"],
    "Pets": ["Name", "Type", "Care Task", "Due Date", "Notes"],
    "Travel": ["Trip", "Start Date", "End Date", "Details", "Location", "Status"],
    "To-Do": ["Task", "Due Date", "Priority", "Category", "Status", "Notes"],
    "Automation Logs": ["Timestamp", "Trigger", "Script", "Result"],
    "Sync Log": ["Date", "Script", "Outcome", "Details"]
}

category_tag_map = {
    "[AGENDA]": "Agenda",
    "[NOTE]": "Notes",
    "[TO-DO]": "To-Do",
    "[ADDRESS]": "Addresses",
    "[SHOPPING]": "Shopping  Wishlist",
    "[BOOK]": "Books  Media",
    "[FITNESS]": "Fitness  Health",
    "[PROJECT]": "Work  Projects",
    "[BIRTHDAY]": "Birthdays  Anniversaries",
    "[CONTACT]": "Contacts  Networking",
    "[AI]": "AI Requests",
    "[FINANCE]": "Finances",
    "[GOAL]": "Goals",
    "[PET]": "Pets",
    "[TRAVEL]": "Travel"
}
